Ruby/RoR-Blog/blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :articles

end

Ruby/RoR-Blog/blog/app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 5 }
end

Ruby/RoR-Blog/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby/RoR-Blog/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def index
        @articles = Article.all
    end

private
    def article_params
        params.require(:article).permit(:title, :text)
    end

end

Ruby/RoR-Blog/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Ruby/RoR-Blog/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/RoR-Blog/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Ruby/RoR-Blog/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Ruby/RoR-Blog/blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

Ruby/RoR-Blog/blog/app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

Ruby/RoR-Blog/blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

Ruby/RoR-Blog/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ruby/RoR-Blog/blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<p>This is Da Wang. Visit wdxtub.com for more.</p>

<%= link_to 'My Blog', controller: 'articles' %>